### ISSUE TITLE
Flash of 404 page when navigating to the releases page

### ISSUE THREAD

**Issue by domyen** [storybookjs/frontpage#115]
https://www.loom.com/share/8fd73c013248491cb224b19caecdf0f3

**Repro**
- Navigate to [deploy preview](https://deploy-preview-109--storybook-frontpage.netlify.app/releases/5.3/)
- Click on Releases link
- See 404 flash into view (right before the content resolves)

**Comment by domyen** [comment]
Can't seem to reproduce this on master.

**Comment by tmeasday** [comment]
Yeah I think this issue is fixed, on prod at least. Let me know if you see it again though, I'm not 100% sure it is fixed in all circumstances (e.g. develeopment)
