### ISSUE TITLE
gatsby-source-github-repo missing on npm

### ISSUE THREAD

**Issue by kylesuss** [storybookjs/frontpage#127]
gatsby-source-github-repo is not available on npm so the builds are failing. Seems like we need to find a replacement.

Example: https://circleci.com/gh/storybookjs/frontpage/501?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link

**Comment by tmeasday** [comment]
@kylesuss it looks like this issue was fixed (/created?) by @dakebl in https://github.com/storybookjs/frontpage/pull/122 -- I think the problem will go away if we merge `master` into `next` your branch. I'll try that now.

**Comment by domyen** [comment]
Yea this was fixed :)
