### ISSUE TITLE
Get 404 when attempting to visit https://storybook.js.org/docs/data

### ISSUE THREAD

**Issue by Too-Far** [storybookjs/frontpage#147]
When attempting to visit https://storybook.js.org/docs/data, I get a 404 redirect page instead.

**Comment by domyen** [comment]
Thanks for the report. That doesn't seem like a valid url. Did this work before? If so, where did it link?

**Comment by Too-Far** [comment]
I haven't ever tried it before, I just followed it tonight looking for some info

**Comment by domyen** [comment]
Got it, I don't think that it was a valid url previously (just looked at webarchive.org). As such, will close this. Thanks for the report!
