### ISSUE TITLE
UI Options link broken

### ISSUE THREAD

**Issue by shrivathsagkumar** [storybookjs/frontpage#151]
The link 
https://storybook.js.org/docs/angular/configure/user-interface 
is broken.

**Comment by domyen** [comment]
Hey @shrivathsagkumar, where did you find the link? AFAICT from a project-wide search we don't link there.

**Comment by shrivathsagkumar** [comment]
Hi,
I found this link under 'Configure Storybook’s UI' section in https://storybook.js.org/docs/angular/configure/overview#configure-story-rendering

**Comment by jonniebigodes** [comment]
@shrivathsagkumar sorry for that small mistake. And @domyen thanks for taking the time for the pull request. I'm going to merge it soon.
