### ISSUE TITLE
Broken links in "Configure your Storybook project"

### ISSUE THREAD

**Issue by lawnchamp** [storybookjs/frontpage#159]
In https://storybook.js.org/docs/react/configure/overview#configure-your-storybook-project there are links to a custom webpack and babel configuration that are broken

### Webpack
**text:** "webpackFinal - custom webpack configuration"
**link:** https://storybook.js.org/docs/react/configure/integration#extending-link: storybooks-webpack-config
  
### Babel
**text:** babel - custom babel configuration.
**link:** https://storybook.js.org/docs/react/configure/integration#babel

<img width="1124" alt="Screen Shot 2020-08-17 at 10 28 50 AM" src="https://user-images.githubusercontent.com/13643618/90407467-917df280-e074-11ea-8f8a-a1315a00bd38.png">

**Comment by domyen** [comment]
Thanks, I believe this is now fixed per [this commit](https://github.com/storybookjs/storybook/commit/cb32b1445ec05979c2bbb7aafd5b75432988d8e7), just awaiting a push to docs from @shilman

**Comment by lawnchamp** [comment]
oh awesome, it is fixed now! Thanks!
