### ISSUE TITLE
"Configure" pages not indexed?

### ISSUE THREAD

**Issue by shilman** [storybookjs/frontpage#163]
When I type in headings from the "Configure" section (e.g. Webpack, Theming, Sidebar, etc.) I only see results from the other sections. It doesn't look like any of those pages are indexed by Algolia?

**Comment by kylesuss** [comment]
https://github.com/algolia/algoliasearch-netlify/#indexing

Reminder for myself: Give this bew plug in a try and see if you get any useful feedback in the crawler ui about why these pages are missing.

**Comment by kylesuss** [comment]
This is fixed now! I got some help from Algolia. I guess I needed to add the sitemap to the config file too 🤦 

https://github.com/algolia/docsearch-configs/commit/87f2fac5482fbd25e84b0f2ce281809ce57100c6
