### ISSUE TITLE
[Bug] Naming and hierarchy page is broken

### ISSUE THREAD

**Issue by mahammedzkhan** [storybookjs/frontpage#187]
**Describe the bug**
The page which displays naming and hierarchy is broken:
https://storybook.js.org/docs/react/writing-stories/naming-components-and-hierarchy

**To Reproduce**

1. Go to https://storybook.js.org/docs/react/writing-stories/naming-components-and-hierarchy
2. See JS error

**Expected behavior**
Ability to read the documentation

**Screenshots**
![image](https://user-images.githubusercontent.com/3067041/99655568-2ae5e780-2a5c-11eb-8343-82217c86e5c8.png)

### Environment

 - OS: [e.g. iOS] Windows
 - Node.js version: [e.g. v12.17.0] N/A
 - NPM version: [e.g. 6.14.4]  N/A
 - Browser (if applicable): [e.g. chrome, safari] Edge
 - Browser version (if applicable): [e.g. 22] 85
 - Device (if applicable): [e.g. iPhone6] Laptop

### Additional context

Shouldn't this be covered through Cypress or something else?
If you disable JS, you can still access it.

**Comment by shilman** [comment]
Fixed. Thanks @mahammedzkhan
