### ISSUE TITLE
Addon page: Twitter card is not valid

### ISSUE THREAD

**Issue by domyen** [storybookjs/frontpage#199]
The `/addons` path of the website doesn't generate a Twitter card. 

When I go here https://cards-dev.twitter.com/validator there is an error.

You can also reproduce by going to twitter, adding the url to a tweet, and seeing if twitter automatically generates a card (it doesn't). 

Thanks for reporting this @pauliescanlon

**Comment by winkerVSbecks** [comment]
@domyen none of the frontpage pages seem to work for Twitter cards. Is this a regression? Because I didn’t touch the base layout.

**Comment by domyen** [comment]
That's strange. I did a cursory search and it doesn't seem like we define
the card meta at all. Perhaps you're right and they never worked.

Docs here:
https://developer.twitter.com/en/docs/twitter-for-websites/cards/guides/getting-started
