### ISSUE TITLE
[Bug] Addon catalog QA

### ISSUE THREAD

**Issue by domyen** [storybookjs/frontpage#205]
**Detail page**
- [x] "View on GitHub" button doesn't link to the Readme
- [x] Relative urls in Readme's don't work – we need to transform the paths like we did with Storybook Documentation
- [x] Change spacing from 16px to 24px here 
![image](https://user-images.githubusercontent.com/263385/105215546-40cc6300-5b06-11eb-8d07-b51947014ad7.png)
- [x] Table elements extend beyond the readme layout
![image](https://user-images.githubusercontent.com/263385/105216172-0fa06280-5b07-11eb-816e-cdd02df6e29c.png)

**Homepage**
- [x] Filter out essential addons from popular list because users can't actually install them (and to make the popular list more dynamic)

**Authors**
- [ ] All the addons in storybookjs/storybook have the same authors. 
![image](https://user-images.githubusercontent.com/263385/105217016-2dba9280-5b08-11eb-9950-39758451b97b.png)

**Search**
- [x] Searching takes multiple seconds, can we make this faster? As a user, I'd expect "instant" (sub-150ms) search.

**Comment by winkerVSbecks** [comment]
> All the addons in storybookjs/storybook have the same authors.

This is because of curated data. Will be fixed once the metadata PRs go out and we can drop curated data.
