### ISSUE TITLE
[Bug] addon detail pages return 404 error page

### ISSUE THREAD

**Issue by seonghyeonkimm** [storybookjs/frontpage#213]
### Describe the bug

- When clicking every addon card item in [addon page](https://storybook.js.org/addons/essentials), it return 404 error page

### Steps to reproduce the behavior

1. Go to  [addon page](https://storybook.js.org/addons/essentials)
2. Click on any addon card item.
3. Then, you can find out 404 error page

### Expected behavior

- When clicking the card item, it should be linked to the proper documentation page.

### Screenshots and/or logs

<img width="1792" alt="스크린샷 2021-01-24 오전 11 53 58" src="https://user-images.githubusercontent.com/13966404/105619939-dafc1600-5e3a-11eb-8e45-b43e70f5ec4e.png">

### Environment

 - Browser (if applicable): chrome (desktop)

**Comment by shilman** [comment]
Fixed now. Thanks for the heads up!
