### ISSUE TITLE
[Bug] Published addon metadata not reflected on catalog

### ISSUE THREAD

**Issue by rbardini** [storybookjs/frontpage#214]
### Describe the bug

The [Paddings addon](https://www.npmjs.com/package/storybook-addon-paddings) metadata has been updated in https://github.com/rbardini/storybook-addon-paddings/commit/43382f541a4465ed7b8b6d146016a0a6a1b446dc, but those changes have not been reflected in the addon catalog a month after.

### Steps to reproduce the behavior

1. Run `npm view storybook-addon-paddings description keywords storybook` to see the package's current metadata.
2. Go to [Paddings addon catalog page](https://storybook.js.org/addons/storybook-addon-paddings).
3. See missing icon and outdated description and category.

### Expected behavior

The page displays the up-to-date icon, description and category from the package's metadata.

### Screenshots and/or logs

```console
$ npm view storybook-addon-paddings description keywords storybook
description = 'Add paddings to view components under different white space settings'
keywords =
[
  'storybook-addons',
  'style',
  'padding',
  'margin',
  'spacing',
  'whitespace'
]
storybook =
{
  displayName: 'Paddings',
  icon: 'https://raw.githubusercontent.com/rbardini/storybook-addon-paddings/HEAD/icon.svg'
}
```

![Screenshot](https://user-images.githubusercontent.com/874370/105630499-e440af00-5e49-11eb-9595-0631207ee461.png)

### Environment

N/A

### Additional context

Paddings addon was previously added to the old addons page in #89, and I could find it in `addons.yml` file until removed in #201.

**Comment by domyen** [comment]
@shilman Is this a crawler issue?

**Comment by shilman** [comment]
`addons.yml` is not synced with the site, so it was using the stale curated data which takes precedence over the crawled data. I've fixed this by hand and we'll come up with a better way to solve this in the future.
