### ISSUE TITLE
[Bug] Missing WebComponents install instructions

### ISSUE THREAD

**Issue by jonniebigodes** [storybookjs/frontpage#228]
### Describe the bug

With a recent change to the documentation that refines the instructions on how to install Storybook for various frameworks, more specifically [this pr](https://github.com/storybookjs/storybook/pull/13591), and how to troubleshoot install instructions. It's now leading to some missing information regarding web components install and the troubleshooting at the bottom of said page. 

### Steps to reproduce the behavior

1. Pull the docs in
2. Run in either development mode /production mode
3. Open `web-components/get-started/install`
4. Open `react/get-started/install`

### Expected behavior

Web Components should load the same as React.

### Screenshots and/or logs
![React-Install-Instrouctions-showing](https://user-images.githubusercontent.com/22988955/108578655-2959e300-731b-11eb-95f5-eb19a07353a0.png)
![WebComponent-Install-Instructions-NoShow](https://user-images.githubusercontent.com/22988955/108578658-2bbc3d00-731b-11eb-924a-1272137b23f1.png)

### Additional context

See `docs/get-started/install` implementation.

The `FeatureSnippets` component for some reason is not loading the `web-components.mdx` file either in the top of the page or in the `TroubleShooting` section.

Feel free to provide feedback

**Comment by geromegrignon** [comment]
@jonniebigodes, sorry to bother you, but could you provide the commands to run the documentation website locally?
I can't find anything in contributing guidance (and would be happy to contribute to improving them).

**Comment by winkerVSbecks** [comment]
@geromegrignon the updated instructions are [here](https://github.com/storybookjs/frontpage#gatsby-instructions): `yarn start:docs-only`

**Comment by jonniebigodes** [comment]
@geromegrignon I pushed an [update](https://github.com/storybookjs/storybook/pull/20011) just a few hours ago, updating the contribution documentation to address issues similar to the one you've faced. It's already merged in. It will require being added to the current version of the documentation as well.

**Comment by winkerVSbecks** [comment]
The frameworks list comes from here: https://github.com/storybookjs/storybook/blob/next/docs/frameworks.js#L2

You're right that the split is probably necessary but we'll need to account for the web-components case.

cc: @kylegach

**Comment by winkerVSbecks** [comment]
Yea, I think you're right. Let's give it a go. We can test with a preview.

**Comment by kylegach** [comment]
Agreed that the `.split` logic can be removed. It seems like `frameworks` used to use a different naming convention?

**Comment by geromegrignon** [comment]
I checked the preview:
- no regression on the existing working frameworks docs
- the installation snippet now works for web-components
