### ISSUE TITLE
Vue edition of storybook tutorial not found

### ISSUE THREAD

**Issue by yogeshwar1996** [storybookjs/frontpage#234]
### Page Not Found

On the page https://storybook.js.org/tutorials/intro-to-storybook/react/en/get-started/ the link to see the Vue edition of story book tutorial is redirecting to a page where it says "NOT FOUND"

### Steps to reproduce the behavior

1. Go to 'https://storybook.js.org/tutorials/intro-to-storybook/react/en/get-started/'
2. Click on hyperlink which says 'Vue'
3. See error

### Expected behavior
It should redirect to https://storybook.js.org/tutorials/intro-to-storybook/vue/en/get-started/ instead of https://storybook.js.org/tutorials/vue/en/get-started

### Screenshots and/or logs

![Screenshot from 2021-02-25 09-03-29](https://user-images.githubusercontent.com/35453051/109099166-a7b5eb00-7748-11eb-8688-885a8c4cf9b1.png)
![Screenshot from 2021-02-25 09-05-23](https://user-images.githubusercontent.com/35453051/109099171-a8e71800-7748-11eb-97ab-46c1bbdeaa05.png)

### Environment

 - OS:  Ubuntu18.04
 - Node.js version:  v12.19.0
 - NPM version: 6.14.4
 - Browser: chrome

**Comment by domyen** [comment]
@jonniebigodes Can you update these urls? 

In the past, we had redirects to handle this case but they were pretty brittle (case in point).

**Comment by jonniebigodes** [comment]
@yogeshwar1996 thank your bringing this to our attention. I'm going to take a look at those links and adjust them accordingly. 

@domyen a pull request will be up shortly.

**Comment by jonniebigodes** [comment]
@yogeshwar1996 once again thank you for bringing this to our attention. I ran the content from end to end and adjusted the links accordingly. Please let me know if any of them is broken. Re-open the issue and point me and i'll take care of it.

Stay safe

**Comment by yogeshwar1996** [comment]
Its working now. Thanks.
