### ISSUE TITLE
[Bug] Some images are broken in the Addon details page

### ISSUE THREAD

**Issue by TheMightyPenguin** [storybookjs/frontpage#242]
### Describe the bug

In some Addon details pages, like the following:

1. https://storybook.js.org/addons/storybook-addon-designs
2. https://storybook.js.org/addons/storybook-dark-mode
3. https://storybook.js.org/addons/storybook-zeplin

The images within the README contents appear broken in the addon details page. Not sure what's the cause, as there are different scenarios:

1. For `storybook-addon-designs` it seems to be using an outdated URL
2. For `storybook-dark-mode` it's using `./example.gif`, which is exactly the value they [set on their README](https://raw.githubusercontent.com/hipstersmoothie/storybook-dark-mode/master/README.md)
3. For `storybook-zeplin`, this is the img src "https://github.com/mertkahyaoglu/storybook-zeplin/blob/master/logo.png", instead of "https://github.com/mertkahyaoglu/storybook-zeplin/raw/master/logo.png"

These may even be an outdated build issue, as these pages are statically generated with Gatsby, maybe a new build will refresh the data and pages and fix the images.

For number `2` tho, it seems like it may be needed to detect URL's that are not absolute, and somehow resolve that properly (e.g.: by prefixing the github raw user content URL?).

I'm still not sure if this is the case, but **I'm up for trying to fix it** if it's other issue and requires research.

### Steps to reproduce the behavior

1. Open any of the links on above
2. Validate that the image appears broken

### Expected behavior

I go to an addon detail pages and the images are working if they also work on their Github README page.

### Screenshots and/or logs

![Screenshot 2021-03-20 150307](https://user-images.githubusercontent.com/11748696/111885436-69999900-898d-11eb-9b32-3c447c943dab.png)

### Environment

 - OS: Windows 10
 - Browser (if applicable): chrome

**Comment by TheMightyPenguin** [comment]
@winkerVSbecks oh I see this is fixed now, nice! Where was it fixed? (just curious about it)

**Comment by winkerVSbecks** [comment]
Github readme's often use relative links for images. Which breaks on npm and the addon catalog. A cleaner approach is to upload images in github issues and then use the full url. The readme's were updated to use those full urls.
