### ISSUE TITLE
Website docs jitter on scroll.

### ISSUE THREAD

**Issue by AndrewSouthpaw** [storybookjs/frontpage#243]
**Describe the bug**

Go to https://storybook.js.org/docs/react/get-started/introduction on Chrome 87 and scroll.

See screengif.

![demo](https://user-images.githubusercontent.com/5187404/102525063-a3859700-404e-11eb-96d2-b294dc70cdb7.gif)

Maybe it's just my machine?

**Comment by domyen** [comment]
First time I've seen this. Going to close, happy to reopen if it's a widespread issue.

(It doesn't happen on my machine)

**Comment by AndrewSouthpaw** [comment]
Yeah problem seems to have gone away for me too. Maybe Chrome was just having a day. 🤷🏼‍♂️
