### ISSUE TITLE
Refactor all images to use gatsby-image

### ISSUE THREAD

**Issue by isaac-martin** [storybookjs/frontpage#25]
No images are using gatsby image - this will help with performance in #12 
Docs are here. https://www.gatsbyjs.org/packages/gatsby-image/

i'm opening this but probably won't have time to look at it for the next little while.

**Comment by domyen** [comment]
Sweet! I'm definitely stoked to see how `gatsby-image` works when implemented well. 

I ran into an early hiccup trying it out (probably my own fault) so decided to wait for someone with more gatsby experience to come along. 🙏

**Comment by isaac-martin** [comment]
Cool - let me see if i can get a half finished PR request implementing it on a couple of our images. That will open it up for wider implementation for everyone else who can dig in!

**Comment by dakebl** [comment]
Any update on this @isaac-martin?
