### ISSUE TITLE
[Bug] Addon is not added to the catalogue

### ISSUE THREAD

**Issue by SimeonC** [storybookjs/frontpage#258]
### Describe the bug

I have followed the steps in the "add new addon" catalogue and my addon is still not showing up in the catalogue. As far as I can tell my package.json is setup correctly with all the right data. Could someone have a look and see if I'm missing something? Thanks.
Addon: https://github.com/SimeonC/storybook-xstate-addon

### Steps to reproduce the behavior

1. Go to the storybook catalogue
2. Search for 'xstate'
3. No results show up

### Expected behavior

I should see my addon in the list.

**Comment by domyen** [comment]
Hey that's strange. It seems your package.json details are correct and it's been a few hours so the crawler should have picked it up. I'll look into it further. Thanks for the report @SimeonC

**Comment by winkerVSbecks** [comment]
@SimeonC your addon was using the `displayName` as `Addon Kit`. The catalog filters out all such addons. Looks like you updated it. We'll trigger another crawl and it should be picked up now.

**Comment by SimeonC** [comment]
Ahh so I just wasn't patient enough after my last attempt. It's showing up now thanks for helping!
