### ISSUE TITLE
Addons catalog: @storybook/addon-xxx display the repo's top-level README

### ISSUE THREAD

**Issue by kaelig** [storybookjs/frontpage#263]
**Describe the bug**

Several `@storybook/addon-xxx` addon pages in the catalog (https://storybook.js.org/addons) display the top-level README instead of their own READMEs.

**To Reproduce**

Not sure all addons are impacted, but these were:

- https://storybook.js.org/addons/@storybook/addon-backgrounds
- https://storybook.js.org/addons/@storybook/addon-a11y

![Screen Shot 2021-05-05 at 11 35 53 AM](https://user-images.githubusercontent.com/85783/117192028-1db47f00-ad96-11eb-8c91-17b364393d11.png)

**Comment by shilman** [comment]
This was a bug in the `package.json` of `addon-a11y` and AFAIK doesn't affect any of the other addons. @coderkevin and I fixed the problem and it should propagate through the system over the next few weeks (I probably need to do another 6.3.x release first, etc.). I'll follow up here when it's fixed.

**Comment by shilman** [comment]
Fixed: https://storybook.js.org/addons/@storybook/addon-a11y
