### ISSUE TITLE
[Bug] 404 error on page for storybook-addon-i18n (was working yesterday)

### ISSUE THREAD

**Issue by greg84** [storybookjs/frontpage#277]
### Steps to reproduce the behavior

1. Go to https://storybook.js.org/addons/storybook-addon-i18n/
2. See 404 error

### Expected behavior

No 404 error. This page was working up to yesterday.

**Comment by domyen** [comment]
Thanks for the report Greg. It's working today when I navigate to that page. Might have been a blip in the CDN? Closing for now, if it's still an issue please re-open.
