### ISSUE TITLE
[Bug] Many (popular) addons lead to 404 pages

### ISSUE THREAD

**Issue by stefan-schweiger** [storybookjs/frontpage#283]
### Describe the bug

Many addons on the frontpage currently lead to a `404 Page not found`

Examples:
https://storybook.js.org/addons/chromatic/
https://storybook.js.org/addons/@storybook/addon-postcss/
https://storybook.js.org/addons/storybook-addon-angular-ivy/
https://storybook.js.org/addons/@geometricpanda/storybook-addon-badges/

But some still work without a problem:
https://storybook.js.org/addons/@storybook/addon-links/

### Screenshots and/or logs

![image](https://user-images.githubusercontent.com/3532342/125438639-1cfb22b1-9a17-4259-a937-0fa9568b2927.png)

**Comment by adrianbielawski** [comment]
My addon also doesn't work https://storybook.js.org/addons/storybook-color-picker/

**Comment by domyen** [comment]
All the addon pages appear to be working when I click on them. @winkerVSbecks do you know anything about why this could happen?

**Comment by winkerVSbecks** [comment]
Working here too. There was a Netlify outage earlier. I wonder if that caused the issue.

**Comment by stefan-schweiger** [comment]
@domyen @winkerVSbecks seems to be working again, so probably it was the Netlify outage. Thanks anyways!
