### ISSUE TITLE
Would you be interested in having a PR with a Github workflow to replace Circle Ci?

### ISSUE THREAD

**Issue by riccardogiorato** [storybookjs/frontpage#292]
## Hello Storybook team!

![](https://i.pinimg.com/originals/9e/a7/2e/9ea72ef078139ced289852e8a4ea0c5c.gif)

Would you be interested in having a PR with a Github workflow to replace Circle Ci? 😃

Would you be open to accept this PR if it takes less time than Circle Ci to do the same steps? 
Are you required to use only Circle Ci for the frontpage project for some legal reasons?

Thank you for storybook and for chromatic @domyen!

**Comment by winkerVSbecks** [comment]
Hey @riccardogiorato, not really. It's an unnecessary disruption without much benefit. Plus it'll require a design change across multiple repos, since we credit CircleCI in the footer.
