### ISSUE TITLE
[Bug] Addon not included in Catalog: storybook-addon-rtl

### ISSUE THREAD

**Issue by literalpie** [storybookjs/frontpage#299]
### Describe the bug

I have followed the instructions in the guide, but the addon is not showing in the addon catalog. It has been almost 48 hours since I last updated the information.

### Steps to reproduce the behavior

Search for "rtl" in the addon catalog (you may need to add, and then remove a space). Some similar addons exist, but this one is not shown: `storybook-addon-rtl`

### Additional context

I'm not totally sure which properties are required. 
* I wouldn't really expect `preset.js` to be required since it's possible for an addon to exist without that file, but I have refactored the addon to have that file.
* There is not an icon for the addon, so that could be the cause, but I don't think so since some other addons have a default icon.

Any help is appreciated, thanks!

**Comment by winkerVSbecks** [comment]
It's been enabled. Will show up on the site in a few hours when the new build is deployed.
