### ISSUE TITLE
[Bug] Use cases / Atlassian & Algolia buttons don't work

### ISSUE THREAD

**Issue by kaelig** [storybookjs/frontpage#307]
### Steps to reproduce the behavior

1. Go to https://storybook.js.org/use-cases
2. Scroll down to the "Create components", see logos that appear below the animation
2. Click on Atlassian or Algolia logos

### Expected behavior

Animation switches to the appropriate brand's one.

### Screenshots and/or logs

<img width="983" alt="Screen Shot 2021-11-01 at 9 35 07 PM" src="https://user-images.githubusercontent.com/85783/139787812-f0e810b4-2187-409d-8a8f-76e6e0d97d02.png">

### Environment

- Chrome 95.0.4638.54
- macOS 12.0.1

**Comment by domyen** [comment]
Thanks for reporting, it's fixed now 🙏
