### ISSUE TITLE
[Bug] Blog search links broken

### ISSUE THREAD

**Issue by shilman** [storybookjs/frontpage#349]
### Describe the bug

1. Go to the blog homepage: https://storybook.js.org/blog/
2. Type a query in the search box. The results are reasonable.
3. Click on a result => nothing happens.

Have tried this in both Chrome & Safari on MacOS so I think it's a problem with the site and not a browser issue (but haven't dug in)

**Comment by winkerVSbecks** [comment]
@shilman seems to work fine for me. It's all client side search so, I'm wondering if it is slow to load.
