### ISSUE TITLE
[Bug] page 404

### ISSUE THREAD

**Issue by tobemaster56** [storybookjs/frontpage#364]
### Describe the bug

when i visit this page， 

https://storybook.js.org/docs/6.5/react/configure/webpack#bundle-splitting

it reports 404, i visit this page from 

https://storybook.js.org/blog/storybook-performance-from-webpack-to-vite/

![image](https://user-images.githubusercontent.com/8998761/167574871-0758b6b1-3a60-42d2-a9d6-05a6fc4e7422.png)

**Comment by winkerVSbecks** [comment]
Yea, that page moved: https://storybook.js.org/docs/6.5/react/builders/webpack#code-splitting

I'll update the post too. Thanks
