### ISSUE TITLE
[Bug] Missing Readme from Addon detail

### ISSUE THREAD

**Issue by pomali** [storybookjs/frontpage#371]
### Describe the bug

README.md is not loading into addon detail for https://storybook.js.org/addons/storybook-addon-stylerscloud 

### Steps to reproduce the behavior

1. Go to https://storybook.js.org/addons/storybook-addon-stylerscloud 
2. Readme is missing
3. Open github/npm and see that README.md is there

### Expected behavior

Readme should be visible 😅

**Comment by winkerVSbecks** [comment]
It's a private repo: https://github.com/stylers-cloud/storybook-addon-stylerscloud so we can't access the files from it.

**Comment by pomali** [comment]
Thank you for info 🙂 maybe it should be added to docs, since in documentation there is only mention of npm.
