### ISSUE TITLE
Remember 'framework' choice across multiple visits to the site

### ISSUE THREAD

**Issue by winkerVSbecks** [storybookjs/frontpage#395]
Folks that use frameworks other than React have to constantly change the URL as google searches always point to 'react'.

I'm not sure how we would implement this with out current architecture. We could track framework choice in local storage, check for it on load and redirect.

Suggested by https://discord.com/channels/486522875931656193/490822681307119618/1025744945685991525

**Comment by thedamon** [comment]
This would be amazing to haveMaking it "opt in" ("Remember my framework choice on this browser", or a separate drop-down to save framework preference) might be another way to look at this which would have less chance of confusing folks and could aid implementation

**Comment by iamkelv** [comment]
> Folks that use frameworks other than React have to constantly change the URL as google searches always point to 'react'.
> 
> I'm not sure how we would implement this with out current architecture. We could track framework choice in local storage, check for it on load and redirect.
> 
> Suggested by https://discord.com/channels/486522875931656193/490822681307119618/1025744945685991525

Is there a valid link to the **dev guide**  which will be a reference when the link is clicked? because the present link is invalid.

If there's and active link then I will like to work on the issue?

**Comment by iamkelv** [comment]
@winkerVSbecks  what is mean is on https://storybook.js.org/addons/@storybook/addon-docs#framework-support when you click on the **dev guide** it direct you to 404 page as shown below

![dev gude](https://user-images.githubusercontent.com/33808005/214602783-fe15570a-623f-4d38-94c1-5bf3d2be21a6.png)
![404](https://user-images.githubusercontent.com/33808005/214602817-0329f701-03f9-487c-8bf6-0e21efee64df.png)

**Comment by winkerVSbecks** [comment]
That's the Storybook docs addon. This issue is regarding the https://storybook.js.org/docs/ website. The two are not related. 

If you're interested in contributing to the Docs addon, here's the guide: https://github.com/storybookjs/storybook/blob/next/code/addons/docs/docs/multiframework.md
