### ISSUE TITLE
[Bug] Issue with development set up

### ISSUE THREAD

**Issue by jonniebigodes** [storybookjs/frontpage#399]
### Describe the bug

After following the instructions outlined [here](https://storybook.js.org/docs/react/contribute/new-snippets#preview-your-work) when a user starts the website with `yarn start:skip-addons`, he's faced with the following errors in the console:

![gatsby-cli-issue](https://user-images.githubusercontent.com/22988955/196266685-1a3b163c-a026-4f67-9ec2-d3f39debea12.png)

Although the build is able to proceed, upon opening up the Storybook website at `http://localhost:8000` he's once again faced with the following:

![frontpage-issue-1](https://user-images.githubusercontent.com/22988955/196266919-88dc4a6a-78a9-4e9a-8aba-726a217c4893.png)

After closing that error message and navigating to the docs page, he's faced with yet another error message:

![fronpage-issue-2](https://user-images.githubusercontent.com/22988955/196267004-5c396c7c-9977-433f-ba64-5b8e2f77d043.png)

I've experienced this myself just now after pulling in the latest changes from `master`.  Based on a cursory search, it seems that Gatsby is asking for environment variables that I haven't set up or other users shouldn't have access to. 

Moving forward and allowing users to be able to spin up the website, some changes are in order, probably something like we're doing with the environment variable added in the `start:skip-addons`.

Should the documentation require an update to address this, let me know, and I'll take care of it.

Feel free to provide feedback.

cc @kylegach and @winkerVSbecks 

Originally reported [here](https://github.com/storybookjs/storybook/pull/19490#issuecomment-1281071912)

**Comment by winkerVSbecks** [comment]
I believe this is because we need credentials to make queries for the homepage. I’ll look at an alternative option so that folks can run it without the creds.

**Comment by jonniebigodes** [comment]
Thanks for looking into this @winkerVSbecks appreciate it 🙏 !
