### ISSUE TITLE
[Question] Listing addon in catalog

### ISSUE THREAD

**Issue by TomFreudenberg** [storybookjs/frontpage#401]
Hi,

I have added a storybook addon functionality to my component:

https://github.com/TomFreudenberg/next-auth-mock

Now I tried to complete the registration for the addon catalog from: 

https://storybook.js.org/docs/react/addons/addon-catalog/

The requirements can not be filled like described on the page:

name: https://github.com/TomFreudenberg/next-auth-mock/blob/master/package.json#L2
preset.js: https://github.com/TomFreudenberg/next-auth-mock/blob/master/package.json#L10

May it be possible to be listed on catalog with this package.json and structure as well?

Otherwise I have to create a single only npm to get listed on addon catalog - ???

Thanks for some guidiance
Tom

**Comment by winkerVSbecks** [comment]
Hi @TomFreudenberg, I'm not sure I follow. Particularly this part: 

> May it be possible to be listed on catalog with this package.json and structure as well?
> Otherwise I have to create a single only npm to get listed on addon catalog - ???

The config in your `package.json` looks good to me. 

The catalog works by scraping npm however, it hasn't picked up your addon. Did you publish it after adding the Storybook addon to your package?

**Comment by TomFreudenberg** [comment]
Hi Varun @winkerVSbecks 

no, I added it before publishing the NPM

What do I mean with:

> May it be possible to be listed on catalog with this package.json and structure as well?
> Otherwise I have to create a single only npm to get listed on addon catalog - ???

Currently if you look at the npm it consists of "two" npm's if we may say for a moment.

1st: npm with general MockSessionContext (src/index.js)
2nd: (npm) with storybook addon in subfolder src/storybook

Therefor it is not only a npm in conjunction with storybook.

For that I am not sure if this meets the requirements for catalog or if I had to move the subfolder "storybook" in a separate npm called next-auth-mock-storybook with a separate package.json.

I would like to do not but maybe it won't never fit the catalog requirements otherwise?

Hope I could bring out the message :-)

**Comment by winkerVSbecks** [comment]
Ah okay. Sorry I got confused by your use of "npm".

NPM is the package registry and what you publish are the packages. Right now you just have one. That's totally fine. If you publish it again with the current changes (that is, the storybook property in `package.json`), it should be picked up by the addon catalog. 

The catalog crawls NPM a couple times in a day. Let me know when you publish the updates. I'll check to see if it was crawled successfully or not.

**Comment by TomFreudenberg** [comment]
Hi Varun @winkerVSbecks

thanks for helping and guiding me again.

I have published a new release with the updated package.json

Sorry that I missed, I hadn't pushed already.

Cheers
Tom

**Comment by TomFreudenberg** [comment]
Super, it worked
