### ISSUE TITLE
[NOT A BUG] a question regarding the usage of nextjs and gatsby

### ISSUE THREAD

**Issue by akafaneh** [storybookjs/frontpage#408]
I didn't find a discussion section on this repo so i didn't know where to ask elsewhere, i saw in a blog post of yours about the revamp of the website that you use gatsby and nextjs, i tried to figure out how it is all connected but i failed, is there any place to look how you done that tech wise?

is it a monorepo with microfrontends kind of arch? or just iframes?
great work btw!

![Screenshot 2022-11-02 at 15 50 45](https://user-images.githubusercontent.com/24367872/199522342-fef52c20-78c4-441e-8d42-82da9ba8b330.png)

**Comment by winkerVSbecks** [comment]
Hey @akafaneh great question. The site is actually multiple JAMstack sites deployed under one domain. We use Netlify redirects and reverse proxy to deploy subsections at specific paths (`/blog` and `/showcase`) 

Most pages lives in this repo but blog and showcase are in separate repositories. We have a design system and a set of shared components that are used across all the projects.

**Comment by akafaneh** [comment]
> Hey @akafaneh great question. The site is actually multiple JAMstack sites deployed under one domain. We use Netlify redirects and reverse proxy to deploy subsections at specific paths (`/blog` and `/showcase`)
> 
> Most pages lives in this repo but blog and showcase are in separate repositories. We have a design system and a set of shared components that are used across all the projects.

thanks for the reply, the website looks cool and what you've done is interesting!
