### ISSUE TITLE
[tailwindcss]: tailwindcss Integration recipe won't work

### ISSUE THREAD

**Issue by DreamWorld420** [storybookjs/frontpage#477]
## Details

**Recipe Page**: [tailwindcss](https://storybook.js.org/recipes/tailwindcss)
**Recipe Template**: [tailwindcss](https://github.com/storybookjs/frontpage/blob/main/src/content/recipes/tailwindcss.md)
**Browser**: Firefox 109.0 (64-bit)

## What is wrong

the provided recipe instruction is outdated and won't work.

-   Suggestions:

    -   Build Tailwind next to Storybook:
        1. script `"build:storybook": "storybook build"` could be changed to `"build:storybook": "build-storybook"`
        2. script `"watch:storybook": "storybook dev -p 6006"` could be changed to `"watch:storybook": "start-storybook dev -p 6006"`

-   Problems:
    -   Provide Tailwind to stories:
        1. to provide tailwind to stories, the css file that was generated by `build:css` and `watch:css` should be imported into preview.js:
        ```js
        import "../public/globals.css";
        ```

**Comment by winkerVSbecks** [comment]
@DreamWorld420 the issue isn't clear. 

> `"build:storybook": "storybook build"` could be changed to `"build:storybook": "build-storybook"`
Not really. `build-storybook` and `start-storybook` was the older version which is being deprecated. 

As for `import "../public/globals.css";`, that assumes that your app is configured to import CSS files. That's not true for all users. Hence we recommend importing CSS via `./storybook/preview-head.html `. Now, if the import path is incorrect then let us know.

**Comment by Integrayshaun** [comment]
@DreamWorld420 I've added a PR #482 to address this.
