### ISSUE TITLE
Logo SVG in /docs/ is now 404ing

### ISSUE THREAD

**Issue by alexlouden** [storybookjs/frontpage#48]
Just noticed in the docs the SVG logo is missing: https://storybook.js.org/docs/basics/introduction/

SVG url: https://storybook.js.org/images/logos/logo-storybook.svg

![Screen Shot 2019-05-27 at 12 42 38 pm](https://user-images.githubusercontent.com/1332954/58395992-434e8f00-807d-11e9-983e-fe4e2fe82695.png)

Had a quick poke around to see if I could see what caused it, maybe was introduced by #47?

**Comment by domyen** [comment]
Thanks for reporting will get out a fix!
