### ISSUE TITLE
[tailwindcss]: outdated code example, no hot reload

### ISSUE THREAD

**Issue by mszekiel** [storybookjs/frontpage#480]
## Details
**Recipe Page**: [tailwindcss](https://storybook.js.org/recipe/tailwindcss)
**Recipe Template**: [tailwindcss](https://github.com/storybookjs/frontpage/blob/main/src/content/recipes/tailwindcss.md)
**Browser**: Chrome 109.0.5414.119 (Official Build) (arm64)

## What is wrong

Hi, I've been previously using tailwind for storybook via adding postcss loaders. In this recipe hot reload for tailwind is not working, as header is loaded only once from what I know. So styles will never update until you refresh the site.

Also the header file will never be able to import `/tailwind.css` from `public` folder until you add `staticDirs` in `main.js`. There're also no details about where the `src/tailwind.css` file comes from, it would be nice to mention that this is the import of root css file where tailwind is being applied. 

Attached code example promotes using `yarn` which causes it to not work by default when you're using `npm`. I would recommend to apply `npm-run-all` as a replacement for `concurrently` package as it's providing simply utility to create such commands
```json
"storybook": "run-p watch:*",
"build-storybook": "run-p build:*",
```

Also, the example code and content of the recipe is assuming `storybook@7` when the recipe header says about `Storybook >=6.0`. In that case using fresh storybook init with version `6.x` will cause the commands `storybook dev` or `storybook build` to not work.

// EDIT
Wth storybook@7 and `@storybook/nextjs` this in `preview.ts` is enough to make tailwind work with hot reload
```js
import "../src/index.css"
```

**Comment by Integrayshaun** [comment]
Hey @mszekiel!!! 

I appreciate you sharing your feedback! I've opened a PR to make these changes to the recipe if you'd like to make sure i've captured everything
