### ISSUE TITLE
[vuetify]: v-app-bar, v-footer, v-navigation-drawer

### ISSUE THREAD

**Issue by 72haja** [storybookjs/frontpage#488]
## Details
**Recipe Page**: [vuetify](https://storybook.js.org/recipes/vuetify#vuetify)
**Recipe Template**: [vuetify](https://github.com/storybookjs/frontpage/blob/main/src/content/recipes/vuetify.md)
**Browser**: Chrome Version 110.0.5481.100

## What is wrong
I tried to write a storybook for my own vuetify 3 library (vue 3 with composition API). Everything works fine (v-btn, v-input, ...) until I tried to include `v-app-bar`, `v-footer` and `v-navigation-drawer` (See error below). I tried adding `<v-app>` to the decorators in preview.js, but i does not compile. It's still `<v-app>` in the devtools editor.

```
// .storybook/withVeutifyTheme.decorator.js
import { useTheme } from "vuetify";

export const DEFAULT_THEME = "light";

export const withVuetifyTheme = (story, context) => {
  const globalTheme = context.globals.theme || DEFAULT_THEME;

  return {
    components: { story },
    setup() {
      const theme = useTheme();

      theme.global.name.value = globalTheme;

      return {
        theme,
      };
    },
    template: `<v-app><story /></v-app>`,
  };
};
```
FYI I didn't forget to use the vuetify plugin under index.js.

```
/**
 * plugins/index.js
 *
 * Automatically included in `./src/main.js`
 */

// Plugins
import { loadFonts } from './webfontloader'
import vuetify from './vuetify'

export function registerPlugins (app) {
  loadFonts()
  app.use(vuetify)
}
```

Does anyone have any ideas?

## Screenshots
![image](https://user-images.githubusercontent.com/33123196/220401476-961be1d4-d541-4d8f-8df6-eba1f2f9bf2c.png)

![image](https://user-images.githubusercontent.com/33123196/220401716-0ad1c013-764f-4c9e-9b15-c97cd231ddba.png)

**Comment by 72haja** [comment]
It works if I put the `v-app` inside the component, but this shouldn`t be the solution I guess.
```
<script setup>
const emits = defineEmits(['menu-click']);

function handleMenuClick () {
  emits('menu-click');
}
</script>

<template>
  <v-app>
    <v-app-bar v-bind="$attrs">
      <template v-slot:prepend>
        <v-app-bar-nav-icon
          @click="handleMenuClick">
        </v-app-bar-nav-icon>
      </template>

      <template v-slot:append>
        <slot name="actions">
        </slot>
      </template>
    </v-app-bar>
  </v-app>
</template>
```

**Comment by Integrayshaun** [comment]
Hey @72haja Thank you for bringing this up! I'm going to spin up my example repo now to see what I can come up with to solve this

**Comment by Integrayshaun** [comment]
Good news! I have figure out how to fix this situation and have updated my [example app](https://github.com/Integrayshaun/vue3-vuetify-storybook-recipe-example) to take this into consideration.

I'll update the recipe now but in the meantime here are the steps

Create a vue component that will wrap your stories in v-app. 

`.storybook/StoryWrapper.vue`
```vue
<template>
  <v-app :theme="themeName">
    <v-main>
      <slot name="story"></slot>
    </v-main>
  </v-app>
</template>

<script>
export default {
  props: {
    themeName: String
  },
}
</script>
```

Then update your `.storybook/withVeutifyTheme.decorator.js` file to look like this:

```js
// .storybook/withVeutifyTheme.decorator.js
import { h } from "vue";
import StoryWrapper from "./StoryWrapper.vue";

export const DEFAULT_THEME = "light";

export const withVuetifyTheme = (storyFn, context) => {
  const globalTheme = context.globals.theme || DEFAULT_THEME;
  const story = storyFn();

  return () => {
    return h(
      StoryWrapper,
      { themeName: globalTheme },
      {
        story: () => h(story, { ...context.args }),
      }
    );
  };
};
```
This makes sure that your story gets wrapped in v-app with the globalTheme set while forwarding your args to the story

**Comment by 72haja** [comment]
It works wonderfully. Thank you!!

**Comment by Integrayshaun** [comment]
Sweet!!!! I'm glad that it worked out for you 🙏
Happy theming!
