### ISSUE TITLE
[next]: Error: No configuration files found with Next.js and Storybook

### ISSUE THREAD

**Issue by heildionis** [storybookjs/frontpage#505]
When trying to run Storybook with Next.js, the error message "No configuration files have been found in your configDir (C:\Users\densa\OneDrive\Рабочий стол\Файлы\Programmes\Projects\Web\Typescript\baking-bread\client.storybook)" is displayed and I can't run Storybook. I am using the latest version of both Storybook and Next.js.

I'm installed react, react-dom, next and then installed storybook with command: 
npx storybook@next init

![image](https://user-images.githubusercontent.com/105888081/226088372-5201fc3b-297a-4cbd-812d-d5b98f39d18f.png)
![image](https://user-images.githubusercontent.com/105888081/226088381-48d7a973-219a-4297-b08d-65c5cedf245a.png)

![image](https://user-images.githubusercontent.com/105888081/226088504-43842d18-19c6-43e3-84b6-cbcd36b66ce4.png)

**Comment by winkerVSbecks** [comment]
@heildionis this is the repo for the Storybook website. Please open an issue on https://github.com/storybookjs/storybook instead with a reproduction. Or drop by the #support channel in the [Storybook Discord](https://discord.gg/storybook)
