### ISSUE TITLE
[Bug] Controls page crashes on firefox

### ISSUE THREAD

**Issue by KrastanD** [storybookjs/frontpage#516]
### Describe the bug

When attempting to access the controls page on firefox it crashes.

### Steps to reproduce the behavior

1. Go to [Controls Page](https://storybook.js.org/docs/react/essentials/controls) using Firefox
2. Observe it crash

### Expected behavior

Expected behavior is to see the content on that page, currently visible with Chromium browsers

### Screenshots and/or logs

![Screenshot of console](https://user-images.githubusercontent.com/32044675/229637171-16ebc634-86fe-40aa-85b9-c90202ab09f4.png)

### Environment

 - OS: [MacOS]
 - Node.js version N/A
 - NPM version: N/A
 - Browser (if applicable): Firefox
 - Browser version (if applicable): 111.0.1 (64-bit)
 - Device (if applicable): M1 Macbook Pro

**Comment by winkerVSbecks** [comment]
Are you running any extension that might be interfering? 
I'm able to run on Firefox without any issues. M1 Macbook Pro too.

Could you maybe clear cache and try again.

<img width="1258" alt="CleanShot 2023-04-03 at 20 12 48@2x" src="https://user-images.githubusercontent.com/42671/229653773-8598dc29-9c73-4f0f-8d5a-57f42043e385.png">

**Comment by KrastanD** [comment]
It was an extension as you guessed. Specifically: https://addons.mozilla.org/en-US/firefox/addon/videospeed/. Thanks!
