### ISSUE TITLE
[vuetify]: can not import registerPlugins

### ISSUE THREAD

**Issue by jonaslbd** [storybookjs/frontpage#522]
## Details
**Recipe Page**: [vuetify](https://storybook.js.org/recipes/vuetify)
**Recipe Template**: [vuetify](https://github.com/storybookjs/frontpage/blob/main/src/content/recipes/vuetify.md)
**Browser**: 

## What is wrong

[vite] Internal server error: Failed to resolve import "../src/plugins" from ".storybook/preview.js". Does the file exist?

it just does not work, could you re-check the instructions? thanks.

**Comment by Integrayshaun** [comment]
Hi @jonaslbd 👋 

Can you give me some more information about your project, please?

Specifically can I get
- versions of
  - Vue
  - Vuetify
  - Storybook
- How Vuetify is being registered in your Vue app

**Comment by jonaslbd** [comment]
hi @Integrayshaun 

i use:
- vue 3.2.47
- vuetify 3.1.15
- storybook 7.0.7
- JS, no typescript

i tried these instructions here https://storybook.js.org/recipes/vuetify , but it fails when using this line of code in preview.js

`import { registerPlugins } from '../src/plugins'`

Do you have some other source/link to a working integration for my setup above? couldn't find any so far.

Thanks in advance!

**Comment by jonaslbd** [comment]
@Integrayshaun only in the main.js with

`import vuetify from './plugins/vuetify';`

and

`app.use(vuetify);`

i could figure out a way to use app.use for the storybook preview - any tips for this?

**Comment by Integrayshaun** [comment]
Cool! So import vuetify from your plugins into your `.storybook/preview.js` file then register it the same way we do with the registerPlugins function.

It would look something like this:

```js
// .storybook/preview.js

import { setup } from '@storybook/vue3';
import vuetify from '../src/plugins/vuetify';

setup((app) => {
  // Registers vuetify in Storybook
  app.use(vuetify);
});
```

**Comment by Integrayshaun** [comment]
@jonaslbd Huzzah! I'm glad that I could help!
