### ISSUE TITLE
[tailwindcss]: Wrong storybook init command.

### ISSUE THREAD

**Issue by ndland** [storybookjs/frontpage#523]
## Details
**Recipe Page**: [tailwindcss](https://storybook.js.org/recipe/tailwindcss)
**Recipe Template**: [tailwindcss](https://github.com/storybookjs/frontpage/blob/main/src/content/recipes/tailwindcss.md)
**Browser**: Brave v1.50.125

## What is wrong
`npx sb init` in the beginning of the doc should be `npx storybook@latest init`. Running the former sets the `package.json` incorrectly trying to use `start-storybook` instead of the new `storybook` bin.

## Screenshots

<img width="1009" alt="image" src="https://user-images.githubusercontent.com/4358059/234153188-071977d3-f158-4721-b5ec-316fdc5fcde3.png">

**Comment by Integrayshaun** [comment]
Hey @ndland 👋 

Good catch!!! I have #524 up for review with the team to get this closed up ASAP 🙏
