### ISSUE TITLE
[next]: storybook won't launch, freshly installed on a nextjs app

### ISSUE THREAD

**Issue by souhailmerroun** [storybookjs/frontpage#536]
## Details
**Recipe Page**: [next](https://storybook.js.org/recipe/next)
**Recipe Template**: [next](https://github.com/storybookjs/frontpage/blob/main/src/content/recipes/next.md)
**Browser**: Arc Browser Latest

## What is wrong

Upon running `npm run storybook`, I have this error

It seems lik Storybook build process is being killed at 25% during the import loader step for @storybook/mdx2-csf/loader.js.

```
@souhailmerroun ➜ /workspaces/nextjs (main) $ npm run storybook

> my-app@0.1.0 storybook
> storybook dev -p 6006

@storybook/cli v7.0.7

info => Starting manager..
WARN You (or an addon) are using the 'config' preset field. This has been replaced by 'previewAnnotations' and will be removed in 8.0
info Addon-docs: using MDX2
info => Using implicit CSS loaders
info => Using default Webpack5 setup
<i> [webpack-dev-middleware] wait until bundle finished
25% building import loader ./node_modules/@storybook/mdx2-csf/loader.jsKilled
```

I've tested on a fresh Github Codespace with a fresh `nextjs` installation

<img width="811" alt="image" src="https://user-images.githubusercontent.com/8895242/235433053-f0e246aa-177c-4021-ba3e-1f5ace97abd4.png">

**Comment by winkerVSbecks** [comment]
@souhailmerroun this repo is for the Storybook docs site. For any Storybook specific issues, please ask in [Storybook discord](https://discord.gg/storybook) or open an issue on https://github.com/storybookjs/storybook with a proper reproduction.
