### ISSUE TITLE
Outdated page with the description of storybook-multilevel-sort

### ISSUE THREAD

**Issue by prantlf** [storybookjs/frontpage#557]
### Describe the bug

The page at Storybook.js > Integrations about the add-on [Multi-level Sorting of Stories](https://storybook.js.org/addons/storybook-multilevel-sort) is outdated.

### Steps to reproduce the behavior

1. Open https://storybook.js.org/addons/storybook-multilevel-sort
2. Open https://www.npmjs.com/package/storybook-multilevel-sort
3. Open https://github.com/prantlf/storybook-multilevel-sort
4. Compare the three pages

NPM shows the current version in sync with GitHub. Storybook.js shows an older version.

### Expected behavior

Storybook.js should show the most recent version of the add-on documentation.

### Environment

 - OS: MacOS
 - Node.js version: N/A
 - NPM version: N/A
 - Browser (if applicable): all
 - Browser version (if applicable): any
 - Device (if applicable): Macbook

### Additional context

The new documentation is important, because the new version of the add-on supports Storybook 7 and has a different interface. The new version of the add-on was published three weeks ago. Is there some manual step to get the page at Storybook.js > Integrations updated?

**Comment by Integrayshaun** [comment]
Hey @prantlf 👋 

Apologies for this. I'm trying to track down why your README in particular isn't updating but for now I've forced an update so that it will be up to date on the Storybook website.

I'll dig in a little deeper this afternoon to see if I can track this down.

**Comment by prantlf** [comment]
Thanks a lot for the quick look and fix, @Integrayshaun!

I removed the icon next to the title and put the badges on a single line, so that the formatting won't look distorted. Maybe it's some content in the README.md, which the Storybook.js updater rejects?

**Comment by Integrayshaun** [comment]
@prantlf it turns out we were using an outdated dataset for NPM details which included the README. I've patched the scraper so that your readme will now stay up to date with your project :) 

The formatting is still a little wonky but you can follow along with #560 for my work on that.

Have a great weekend. my friend :D
