### ISSUE TITLE
[next]: Using pnpm to install Storybook into a Next.js project

### ISSUE THREAD

**Issue by Seefer** [storybookjs/frontpage#581]
## Details
**Recipe Page**: [next](https://storybook.js.org/recipe/next)
**Recipe Template**: [next](https://github.com/storybookjs/frontpage/blob/main/src/content/recipes/next.md)
**Browser**: Microsoft Edge Version 114.0.1823.82 (Official build) (64-bit)

## What is wrong
Using `create-next-app@latest` (v 13.4.10) to create a project I then proceed to install Storybook with `pnpm dlx storybook@latest init`. During the following prompts, I eventually received the errors in the screenshot.

I'm using pnpm v 8.6.7

## Screenshots
![image](https://github.com/storybookjs/frontpage/assets/129484/dcb81a96-652a-4465-8882-eb6f643d0d38)

**Comment by Integrayshaun** [comment]
Hey @Seefer 👋 

We were talking about this on Discord and it turns out this was a problem with having prettier 2 and 3 in your dependencies.

Is there anything in particular that you'd like me to change about the recipe?

**Comment by Integrayshaun** [comment]
Hey folks 👋 

I'm going to close this issue for now due to inactivity. However, please comment if this is still a problem and I'll reopen it for investigation.
