### ISSUE TITLE
[Bug] In this example Button is a component but is used as a type

### ISSUE THREAD

**Issue by KonradLinkowski** [storybookjs/frontpage#585]
### Describe the bug

On this site https://storybook.js.org/blog/writing-stories-in-typescript/#changes-coming-in-storybook-v7

There are a few examples of using `StoryObj` e.g.:

```
// Button.stories.ts
import { Meta, moduleMetadata, Story } from "@storybook/angular";
import { CommonModule } from "@angular/common";
import { Button } from "./button.component";

export default {
  component: Button,
  decorators: [
    moduleMetadata({
      declarations: [Button],
      imports: [CommonModule],
    }),
  ],
} as Meta<Button>;

export const Primary: Story<Button> = (args) => ({
  props: args,
});
Primary.args = {
  label: "Button",
  primary: true,
  size: "xl",
  // ^ TypeScript error: type of `Button` does not contain `size`
};
```

As you can see `Button` imported here:
```
import { Button } from "./button.component";
```
Is used as a component:
```
component: Button,
```
And also as a type:
```
Story<Button>
````

### Steps to reproduce the behavior

This code will throw ts error:
```
Story<Button>
```

### Expected behavior

`typeof` operator should be used:
```
Story<typeof Button>
```

**Comment by winkerVSbecks** [comment]
Thanks for pointing that out. The article you linked is from almost a year ago, written for SB 6.5. We don't go back to update blog posts. However, the docs are always up to date. The docs now provide TS examples for every code snippet.
