### ISSUE TITLE
[next]:storybook: Error: Cannot find module next/legacy/image

### ISSUE THREAD

**Issue by Alperec** [storybookjs/frontpage#599]
## Details
I updated nextjs to the latest version and decided to move on to storybook version 7, now after launch I get the error Cannot find module 'next/legacy/image'
 
main.ts
```
import type { StorybookConfig } from "@storybook/nextjs";

const config: StorybookConfig = {
    stories: [
        "../stories/**/*.mdx",
        "../stories/**/*.stories.@(js|jsx|mjs|ts|tsx)",
    ],
    addons: [
        "@storybook/addon-links",
        "@storybook/addon-essentials",
        "@storybook/addon-onboarding",
        "@storybook/addon-interactions"),
    ],
    framework: {
        name: "@storybook/nextjs",
        options: {},
    },
    docs: {
        autodocs: "tag",
    },
};
export default config;
```
<img width="988" alt="Снимок экрана 2023-09-14 в 10 23 31" src="https://github.com/storybookjs/frontpage/assets/57576416/b7180129-55c9-4fbe-b822-1445b64f1600">

**Comment by winkerVSbecks** [comment]
This is the repository for Storybook docs. Please open an issue on https://github.com/storybookjs/storybook or drop by our discord: https://discord.gg/storybook
