### ISSUE TITLE
Font families alternate in code blocks

### ISSUE THREAD

**Issue by TomerAberbach** [storybookjs/frontpage#87]
The fonts in the code blocks of many pages (e.g. [Standalone Options](https://storybook.js.org/docs/configurations/standalone-options)) alternate between Ubuntu Mono and Fira Code for me.

It appears that the `#docs-content .markdown code` selector sets `font-family` to `Consolas, Liberation Mono, Menlo, Courier, monospace`. I do not have any of those font families installed so the fallback `monospace` font is chosen, which for me is Ubuntu Mono.

However, the CSS `token` class appears to set `font-family` to `"Operator Mono", "Fira Code Retina", "Fira Code", "FiraCode-Retina", "Andale Mono", "Lucida Console", Consolas, Monaco, monospace`. I happen to have Fira Code installed so that's the font family that is chosen.

The effect that this creates for me is that in a single code block, text enclosed in a span with class `token` is rendered in Fira Code while other text is rendered in Ubuntu Mono. Depending on the fonts installed by other users, their code blocks may alternate between other font families.

I think a good solution would be to only set `font-family` in the `#docs-content .markdown code` selector (perhaps to what the `token` class currently set `font-family` to) and not to set `font-family` at all in the `token` class.

**Comment by domyen** [comment]
Hey Tomer, I think this has either been fixed in the new docs site or doesn't refer to the marketing site. Reopen if still a problem.

**Comment by TomerAberbach** [comment]
Yup, looks like it's fixed in the new docs site!
