### ISSUE TITLE
Website goes blank when accessing https://storybook.js.org/docs/testing/react-ui-testing/

### ISSUE THREAD

**Issue by gabriel-kohen-by** [storybookjs/frontpage#88]
When navigating to the page above, it initially shows up and then disappears after a second or so.
Tested on:
MacBook Pro 2018 10.14.6
Chrome Version 79.0.3945.130 (Official Build) (64-bit)
Safari Version 13.0.4 (14608.4.9.1.4)
See attached logs
[storybook.js.org-1579614792123.log](https://github.com/storybookjs/frontpage/files/4091363/storybook.js.org-1579614792123.log)

**Comment by shilman** [comment]
check your connection and clear your cache? it works for me.

**Comment by gabriel-kohen-jdas** [comment]
Forgot to mention. Was running it in Incognito mode so no cache and connection speed seems to be OK:
![image](https://user-images.githubusercontent.com/57095228/72811070-e36cb000-3c2c-11ea-8ca7-a19b9d9d9901.png)
PING github.com (140.82.114.4): 56 data bytes
64 bytes from 140.82.114.4: icmp_seq=0 ttl=53 time=14.377 ms
64 bytes from 140.82.114.4: icmp_seq=1 ttl=53 time=23.477 ms
64 bytes from 140.82.114.4: icmp_seq=2 ttl=53 time=17.640 ms
64 bytes from 140.82.114.4: icmp_seq=3 ttl=53 time=17.073 ms
64 bytes from 140.82.114.4: icmp_seq=4 ttl=53 time=15.304 ms
64 bytes from 140.82.114.4: icmp_seq=5 ttl=53 time=23.262 ms
64 bytes from 140.82.114.4: icmp_seq=6 ttl=53 time=21.177 ms
64 bytes from 140.82.114.4: icmp_seq=7 ttl=53 time=21.654 ms
64 bytes from 140.82.114.4: icmp_seq=8 ttl=53 time=17.329 ms
64 bytes from 140.82.114.4: icmp_seq=9 ttl=53 time=20.990 ms
Let's see if restart works. Might be intermittent. The rest of the site works fine.

**Comment by gabriel-kohen-jdas** [comment]
Interesting tidbit. I do have Cisco Anyconnect running on my Mac (although not connected). 
It might be related to this issue: https://github.com/storybookjs/storybook/issues/8193

**Comment by shilman** [comment]
Ah I missed the "shows up and disappears" part. Sounds like some JS error. Anything in the browser console?

**Comment by gabriel-kohen-jdas** [comment]
See attached log for stacktrace. Thanks!

**Comment by kylesuss** [comment]
This appears to be fixed. Can reopen if that's not the case.
